# Generated by Django 3.2.8 on 2021-10-15 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(max_length=24, validators=[django.core.validators.RegexValidator(regex='[^@]+@[^@]+\\.[^@]+')]),
        ),
    ]
